apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-deployment
  labels:
    app: furniture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture
  template:
    metadata:
      labels:
        app: furniture
    spec:
      containers:
      - name: furniture
        image: 657570828542.dkr.ecr.us-west-2.amazonaws.com/shopping-site-furniture:f08bb7104806b5b35a1df8e88efe9a35c77e4126
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: furniture-service
  labels:
    app: furniture
spec:
  type: ClusterIP
  selector:
    app: furniture
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
