apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-deployment
  labels:
    app: furniture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture
  template:
    metadata:
      labels:
        app: furniture
    spec:
      containers:
      - name: furniture
        image: 183679577304.dkr.ecr.us-west-2.amazonaws.com/shopping-site-furniture:a1046117e4f7ac9fb7bb30c6c5ae9c35942e7a84
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: furniture-service
  labels:
    app: furniture
spec:
  type: ClusterIP
  selector:
    app: furniture
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
