apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 183679577304.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:a1046117e4f7ac9fb7bb30c6c5ae9c35942e7a84
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    app: main-frontend
spec:
  type: ClusterIP
  selector:
    app: main-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
