apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-deployment
  labels:
    app: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: 183679577304.dkr.ecr.us-west-2.amazonaws.com/shopping-site-food:a1046117e4f7ac9fb7bb30c6c5ae9c35942e7a84
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: food-service
  labels:
    app: food
spec:
  type: ClusterIP
  selector:
    app: food
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
