apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobiles-deployment
  labels:
    app: mobiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobiles
  template:
    metadata:
      labels:
        app: mobiles
    spec:
      containers:
      - name: mobiles
        image: 183679577304.dkr.ecr.us-west-2.amazonaws.com/shopping-site-mobiles:7851538b83b5385caeca59199a2e97bfd4bc3450
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobiles-service
  labels:
    app: mobiles
spec:
  type: ClusterIP
  selector:
    app: mobiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
