apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 657570828542.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:f08bb7104806b5b35a1df8e88efe9a35c77e4126
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlepay-service
  labels:
    app: googlepay
spec:
  type: ClusterIP
  selector:
    app: googlepay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
