apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-deployment
  labels:
    app: fashion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion
  template:
    metadata:
      labels:
        app: fashion
    spec:
      containers:
      - name: fashion
        image: 183679577304.dkr.ecr.us-west-2.amazonaws.com/shopping-site-fashion:a1046117e4f7ac9fb7bb30c6c5ae9c35942e7a84
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-service
  labels:
    app: fashion
spec:
  type: ClusterIP
  selector:
    app: fashion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
