apiVersion: apps/v1
kind: Deployment
metadata:
  name: appliances-deployment
  labels:
    app: appliances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appliances
  template:
    metadata:
      labels:
        app: appliances
    spec:
      containers:
      - name: appliances
        image: 183679577304.dkr.ecr.us-west-2.amazonaws.com/shopping-site-appliances:83429aae4829d856800cf3f9939d35acca902926
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appliances-service
  labels:
    app: appliances
spec:
  type: ClusterIP
  selector:
    app: appliances
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
